GET http://localhost:8080/api/contracts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJ1c2VyIiwiaWF0IjoxNTkyMzk0NTMzLCJleHAiOjE1OTI0MDQ1MzN9.FAP4_1H2OLiYrAyC44nga5RSBVMYNCoz2cbLBptlJKaUFUuMEyLVdTEaTQhGvimo

{
}

###

GET http://localhost:8080/monsters/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjpbIlJPTEVfVVNFUiJdLCJzdWIiOiJ1c2VyIiwiaWF0IjoxNTkxNzM3NTY2LCJleHAiOjE1OTE3NDc1NjZ9.FTBL3PhwEwbQmVwNHhSB80bZVerbpQjO6gX3UoHYAEKAn81CkIWCgr-ZpBUeEcuW

{
}

###
